### ISSUE TITLE
Error during install : "husky: not found"

### ISSUE THREAD

**Issue by scand1sk** [achmadk/react-loading-overlay-ts#1]
Hi, 
I got this error during install:

```
npm ERR! code 127
npm ERR! path /xxx/node_modules/react-loading-overlay-ts
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: 1: husky: not found
```

Maybe a dependency is wrong or missing?

**Comment by achmadk** [comment]
Hello @scand1sk , can you try version `1.0.4-alpha.0` of this library?

```sh
npm i react-loading-overlay-ts@1.0.4-alpha.0
```

if this issue has been disappeared, I will publish 1.0.4.

**Comment by scand1sk** [comment]
Thank you for correcting the issue so quickly. It works on my side now.
