### ISSUE TITLE
findDOMNode is deprecated

### ISSUE THREAD

**Issue by Frankusky** [achmadk/react-loading-overlay-ts#4]
Does there is any way to fix the following warning?

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. 

For future reference, im using: 
react-loading-overlay-ts V2.0.0 
NextJs 12.1.5
Node 16.15.0

**Comment by achmadk** [comment]
fixed in version 2.0.1.

If you are using this library alongside nextjs, you can use dynamic import `next/dynamic`, because this library has a method with `window`.

```ts
import dynamic from 'next/dynamic'

const LoadingOverlay = dynamic(() => import('react-loading-overlay-ts'), {
  ssr: false,
})
```
